### ISSUE TITLE
Empty popup shows on non-text elements when non-Japanese languages are selected

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan#1011]
When hovering over certain non-text html, an empty popup with "No results found" shows up.

For example when I hover over the play button on Youtube 
<img width="649" alt="image" src="https://github.com/themoeway/yomitan/assets/2382537/a91e86c3-0a27-4b2d-be9b-d0c078d6491e">

This does not occur when Japanese is selected.

Extension version: Yomitan 24.4.16.0
Platform: Mac OS
Browser: Chrome
Language: en-US
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
AnkiConnect version: Unknown (Anki not running or connected)
Installed dictionaries: Jitendex.org [2024-04-28]

**Exported settings file**
[known_buggy_yomitan_settings.json](https://github.com/themoeway/yomitan/files/15503285/yomitan-settings-2024-05-30-17-01-57.json)
[known_good_yomitan_settings.json](https://github.com/themoeway/yomitan/files/15503349/yomitan-settings-2024-05-30-17-06-06.json)

Related issues

**Comment by Kajal-11** [comment]
I am trying to replicate this error in order to find a fix. Hovering over an image having no alt text, with English set as language in settings, I am getting a "No results found" popup. With Japanese settings, no popup shows up. Is this behavior also a consequence of the bug mentioned above? 

Also, is the ideally expected behavior that this popup doesn't appear at all?

![en settings](https://github.com/themoeway/yomitan/assets/43801094/42485d30-be38-46ec-a701-f7fa476fcaec)

P.S.- It's on a Windows system.
