### ISSUE TITLE
Yomitan crash displaySetContentScale

### ISSUE THREAD

**Issue by Casheeew** [themoeway/yomitan#1153]
According to an user on discord:
Yomitan gradually becomes slower the more searches he does before Yomitan crashes and self-destructs (once every approx 2 hours)

error dump:
![image](https://github.com/themoeway/yomitan/assets/52880648/b20abbd9-0823-4c19-9437-8644f82c6c63)

**Comment by tomashaddad** [comment]
Related to #922 and #836? This is happening to me too.

Something I did notice is that the memory footprint of Yomitan in Google Chrome task manager is forever increasing when using the shift hover popup. Just slowly shift-ing over words on the search page for a minute has raised it to 500,000K. Perhaps the popups aren't being killed properly?

**Comment by AdriGrana** [comment]
Will these crashing issues ever be addressed? I only see how these cases get closed but don't see anything done about it.

**Comment by Kuuuube** [comment]
This issue was closed as a duplicate. That means there was another issue reporting the same bug. 

In this case the connection between displaySetContentScale and crashing was not correct. The displaySetContentScale error did not cause crashing.

The issue with displaySetContentScale has been fixed but given that the issue had nothing to do with crashing to begin with, the crashing has not been fixed.

Most crashing issues have to do with manifest v3 messing up Yomitan and we cannot fix that until browsers implement more features.

If you have found some way to crash Yomitan which does not have an open issue, please make a new issue reporting it.
