### ISSUE TITLE
Allow replace pattern within popup with  entry term

### ISSUE THREAD

**Issue by khaitruong922** [themoeway/yomitan#1378]
![Screenshot_20240830_180933_Kiwi Browser.jpg](https://github.com/user-attachments/assets/4f343e7a-9461-42c4-adfd-92a9a00a6429)

Some dictionaries have the syntax of using  dash to represent the entry term for words which include it.

We can add a setting (preferably dictionary specific, since each one has different syntax) to replace a pattern with the entry term, so that the words become searchable.

**Comment by khaitruong922** [comment]
![Screenshot_20240830_194526_Kiwi Browser.jpg](https://github.com/user-attachments/assets/8301f42a-dd26-4822-ad1a-83fee65424d6)



This can be a more generic regex functionality for popup. For example, in the above image, I want to remove the small parentheses group `(ぬ)` so that I can search 縫い子.

**Comment by IMakeBotsForYou** [comment]
This is a good idea imo.

**Comment by Kuuuube** [comment]
This feels out of the scope of Yomitan. Dictionaries with entries like this would be best off re-processed outside of Yomitan. Adding dictionary specific behavior within Yomitan for things that can be fixed by editing the dictionary file seems unreasonable.

If this is a common enough thing, maybe it's worth throwing together a script for processing this and having that live in the tmw org. Or maybe an additional feature to yomitan-import.
