### ISSUE TITLE
[English] Search pop-up does not have the focus even though it search new words.

### ISSUE THREAD

**Issue by fideliochan** [themoeway/yomitan#1445]
**Description**
My clipboard monitor setting is on, I select a word and do ctrl c, the pop up searches for that word but the window cannot take the focus on itself, I think it is not productive to constantly do alt tab.
**Browser version**
Edge Version 129.0.2792.52 (Official build) (64-bit)

**Yomitan version**
Yomitan 24.9.16.0

**Exported settings file**
[yomitan-settings-2024-09-25-07-20-35.json](https://github.com/user-attachments/files/17126858/yomitan-settings-2024-09-25-07-20-35.json)

**Comment by Kuuuube** [comment]
This has been discussed in in discord previously https://discord.com/channels/617136488840429598/1278465217344569465/1278465217344569465

It was found out that this is an OS level issue likely due to Windows' window manager. It's unknown whether this is a intended or if it's a regression but it previously did work the way you mention before whatever change was made by Microsoft. Unfortunately there's nothing we can do to fix this in Yomitan.

**Comment by Kuuuube** [comment]
One potential solution would be to set the window to "always on top". You can set up this feature using PowerToys https://learn.microsoft.com/en-us/windows/powertoys/.
