### ISSUE TITLE
Remove KireiCake

### ISSUE THREAD

**Issue by MarvNC** [themoeway/yomitan#195]
https://github.com/FooSoft/yomichan/issues/1608

> A given entry usually has a handful of these qualities:

> straight up wrong
> not entirely wrong, but not particularly accurate
> very incomplete
> has typos / formatting errors / inconsistencies
> vastly inferior to the jmdict entry
> vastly inferior to the jj entries
> very apparent / unneeded A+B

Thermosphere brought this up a while ago, and I feel like it should be removed especially as JMDict has continuously been improving and there isn't much point in KireiCake at all given its inaccuracies.

**Comment by Kuuuube** [comment]
To add to this, I ran a diff of kireicake vs the latest jmdict and a few very old versions of jmdict. There's 7184 terms missing from the latest jmdict that are in kireicake. BUT almost all of these are deleted or rejected entries from jmdict.

Entries deleted or rejected from jmdict are not good to have. They often include completely useless information, words that were mistakenly added and don't actually exist, or completely wrong information.

The vast majority of entries exist in both kireicake and jmdict. However, jmdict has constant updates. There are mistakes in jmdict but over the years those mistakes have been cut down enormously. Kireicake is not updated and still contains every mistake that jmdict from years ago did.

Kireicake also polutes Yomitan's furigana generator with ridiculous ruby text for words. For example, every compound word that contains both katakana and kanji, kireicake will show furigana instead of katakana and add furigana above the hiragana with the katakana. Even just having kireicake enabled at any priority on your dictionary list can cause these issues.

Having kireicake dictionary will only serve to mislead and confuse. I highly recommend any users of kireicake to switch to either [Jitendex](https://jitendex.org/pages/downloads.html) or use an [updated version of JMdict](https://github.com/themoeway/jmdict-yomitan/releases/latest) (if you like the style of old jmdict/kireicake formatting theres a legacy formatted version available too).
