### ISSUE TITLE
Service worker load time

### ISSUE THREAD

**Issue by djahandarie** [themoeway/yomitan#292]
Some people seem to have issues with the service worker taking time to come back online for a new lookup (after not using Yomitan for awhile).

I think we need to do some performance analysis on the service worker load time.

(I also heard that bulk imported dictionaries seem to cause worse performance compared to dictionaries imported one by one? Not sure if it's releated.)

**Comment by jbukl** [comment]
Most likely just the [indexeddb.open](https://github.com/themoeway/yomitan/blob/master/ext/js/data/database.js#L203) call being run whenever the service worker is booted. 

I was getting ~6.5 seconds with just JMDict installed, and ~8 seconds before the [request.onsuccess](https://github.com/themoeway/yomitan/blob/master/ext/js/data/database.js#L215) was reached with these individually imported ones (several of which are very big):

![image](https://github.com/themoeway/yomitan/assets/148171160/588ded5c-a0dc-4378-952c-923023feb3e1)

18 seconds with some random big JSON collection (1.3gb):

![image](https://github.com/themoeway/yomitan/assets/148171160/a05fd125-ae17-4d66-afc2-5ff939989136)
![image](https://github.com/themoeway/yomitan/assets/148171160/cd868320-0851-40c4-9ead-8960b4709f30)

I tested a bit to see the service worker's lifetime, and it seemed like it would be terminated within the 5 minutes [google mentions it to](https://developer.chrome.com/docs/extensions/mv3/service_workers/service-worker-lifecycle/#idle-shutdown) (usually within 30 seconds-2 minutes) when there's no yomitan tabs open, leading to a long cold boot when trying to scan Japanese text again. I assume some settings currently available in the extension being enabled could keep the service worker alive long-term as well, e.g. the backend clipboard monitor, but I didn't test any of that.

I also tried looking into the performance of opening IndexedDB connections with service workers, but I couldn't find too much about it - I can't add much on this with no knowledge of IndexedDB.

Aside from that, [forcibly persisting the service worker](https://stackoverflow.com/questions/66618136/persistent-service-worker-in-chrome-extension) would probably deal with it, although from what I've seen, I think a lot of people are anxious about the long-term viability of those solutions - especially since it feels like a lot of the MV3 stuff is new and uncertain (like `offscreen`).

**Comment by djahandarie** [comment]
Resolved by #325
