### ISSUE TITLE
Google Docs Compatibility Mode stopped working

### ISSUE THREAD

**Issue by Scrub1492** [themoeway/yomitan#451]
**Description**
Cannot scan text using Yomitan, even after enabling Google docs compatibility mode.
![image](https://github.com/themoeway/yomitan/assets/52880648/2ff41787-4f19-4459-80d3-0773a43249b8)

**Browser version**
Chrome Version 120.0.6099.130 (Official Build) (64-bit)

**Yomitan version**
23.11.23.0 Yomitan (development build)

**Exported settings file**
[yomitan-settings-2023-12-26-06-56-10.json](https://github.com/themoeway/yomitan/files/13769346/yomitan-settings-2023-12-26-06-56-10.json)

**Comment by toasted-nutbread** [comment]
#235

**Comment by toasted-nutbread** [comment]
I believe that fixing this requires bumping the minimum chrome version from 96 to 102 in order to support `RegisteredContentScript.world` in Chromium browsers. Firefox can approach this differently.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/RegisteredContentScript#browser_compatibility

@djahandarie thoughts? I'm not sure what the most recently thinking is around bumping minimum browser versions.

**Comment by djahandarie** [comment]
I think we should feel free to bump the required min browser version whenever necessary. Old browser versions tend to have lots of security vulnerabilities, there is little point in trying to maximize compatibility these days.
