### ISSUE TITLE
Scanning using touch input does not work on Firefox for Android

### ISSUE THREAD

**Issue by Lolle2000la** [themoeway/yomitan#489]
**Description**
No matter how I configure the input settings, no text on a web page is ever selected and the popup dictionary never opens when using Yomitan on Firefox for Android. The addons search page works as expected though, including selecting text on its results.

When opening the extension popup once while having navigated to a page, selection will work again. This is just my guess, but I think, Yomitan does not automatically get activated when navigating to a new page/tab on Firefox for Android.

**Browser version**
Firefox for Android 121.0

**Yomitan version**
23.11.23.0

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page; zip or rename the resulting file to .txt to attach to the issue.)

**Comment by afn478** [comment]
I have had a very same problem. Sanity check: Did you enable reommended permissions on the [welcome page](moz-extension://08a17207-fbe6-4fd9-a183-d699ecaf2355/welcome.html)?

![Screenshot_20231229_153616_Firefox.jpg](https://github.com/themoeway/yomitan/assets/83926912/a2e8bbc3-2014-4375-ba6c-129bc843e63f)

(Let me know if the hyperlink worked, otherwise you can access the welcome page in the yomitan settings' general section "show the welcome guide on browser startup")

**Comment by Lolle2000la** [comment]
Thank you! I did not, but that fixed it. I thought it did, but when I checked it wasn't there. Enabling it asked me for permission to access all web pages and then it did indeed work.
