### ISSUE TITLE
JMdict sense numbers are redundant with ordered list numbers in Group Term-reading Pairs

### ISSUE THREAD

**Issue by yangmillstheory** [themoeway/yomitan#506]
Hello; apologies if I'm misunderstanding, but for many definitions I see the following ordered list with the list element number being exactly the same as the JMdict Sense number:

![image](https://github.com/themoeway/yomitan/assets/2729079/7e89c391-8006-49f0-8ed8-bfd66be59ada)

This seems duplicative to me when using grouping mode Group Term-Reading Pairs.

* Is there a reason to keep both (is it possible for one single definition to have multiple senses)?
* Could we turn off the numerical sense icons?

When I import definitions into Anki, I have to do some extra work to remove the sense icons to remove the redundancy.

**Comment by stephenmk** [comment]
> is it possible for one single definition to have multiple senses

Yes.

<details>
  <summary>ミス</summary>

![misu](https://github.com/themoeway/yomitan/assets/8003332/8a7845b2-55ad-42d4-a39e-84e3ae2be508)
</details>

<details>
  <summary>けいそつ</summary>

![keisotu](https://github.com/themoeway/yomitan/assets/8003332/f6036b6a-a93c-46f9-a7cc-4e0f9e9e70a3)
</details>

<details>
  <summary>もと【元】</summary>

![moto](https://github.com/themoeway/yomitan/assets/8003332/213ee535-a5ee-4277-9f10-7e6c080dfb89)
</details>

> Is there a reason to keep both

The JMdict sense numbers aren't always going to be the same as the HTML ordered list numbers. If you have multiple dictionaries and the JMdict senses are displayed below them, then the numbers will be offset by those other entries.

The numbers aren't always going to be sequential within a given JMdict entry, either. Notice that sense #<span>9</span> is missing from the もと【元】 screenshot above. Since the #<span>9</span> definition only applies to the 本 form of the word, the definition has been omitted.

I designed the dictionary that way because I spend a lot of time editing JMdict, and the information is useful for me. I agree that the presentation isn't great and that the information might not be useful for everyone. I think I have improved upon the design in [Jitendex](https://github.com/stephenmk/jitendex#example-4-%E3%81%91%E3%81%84%E3%81%9D%E3%81%A4).

> Could we turn off the numerical sense icons?

They would need to be removed from the dictionary, or you could maybe modify the Yomitan handlebars to strip them out. I'm willing to accept a commission to make a dictionary file without the numbers for you, but I'm afraid it wouldn't be very cheap. Maybe someone else will volunteer to do the work for free.

**Comment by yangmillstheory** [comment]
Thanks for the reply Stephen! I'm still new to the various dictionary schemas and tagging semantics, but it sounds like the numbering is working as intended (indeed, I only spot-checked a few entries).

If I'm the first person that's asked for this, then perhaps it's not worth doing the work to implement this feature, and maybe it doesn't make sense in general. In that case, I'm fine closing the issue as not planned.

BTW I tried Jitindex yesterday, but ran into #504 when mining cards.

**Comment by stephenmk** [comment]
> BTW I tried Jitindex yesterday, but ran into https://github.com/themoeway/yomitan/issues/504 when mining cards.

Correct me if I'm wrong, but it looks like you're using the jp-mining-note anki template. The issue with the SVG images that you had is due to that template, not Jitendex or Yomitan.

I agree that the SVG icons aren't a good solution. I recently [submitted a patch to Yomitan](https://github.com/themoeway/yomitan/pull/450) that will allow Yomitan dictionaries to use more types of CSS styles (`border-radius`, `background-color`, etc.). As soon as this new version of Yomitan is available (probably within the next week?), I am going to release a new version of Jitendex which replaces those SVG icons with plain HTML and CSS. I expect that this new version will resolve the image issues with the jp-mining-note template.

**Comment by yangmillstheory** [comment]
>Correct me if I'm wrong, but it looks like you're using the jp-mining-note anki template.

Nah, I'm using my own hacky HTML and CSS code, though I did suspect that the rendering issue could have been fixed on the user side. If you ping this bug or #504 when the new Jitindex releases, I'd be happy to try it out again.

**Comment by djahandarie** [comment]
>  As soon as this new version of Yomitan is available (probably within the next week?)

@stephenmk I just promoted the https://github.com/themoeway/yomitan/releases/tag/23.12.29.0 release from dev to stable, so go for it! :pray:

**Comment by yangmillstheory** [comment]
Continuing the conversation in #504.

**Comment by Kuuuube** [comment]
Closing as this is a dict issue not a yomitan issue.
