### ISSUE TITLE
Add better ways to close popup for mobile

### ISSUE THREAD

**Issue by Kuuuube** [themoeway/yomitan#509]
Currently, exiting the popup on mobile requires clicking off of the popup. This can cause unintended interactions with the page.

The best way to fix this is probably to handle it similarly to jidoujisho where the popup can be swiped to the side and disappears.

If it's unreasonable to add in the above way, simply adding an X button near the top of the popup would help a lot.

Here's an example of what it looks like in jidoujisho:
![jidoujisho_swipe_](https://github.com/themoeway/yomitan/assets/61125188/2731a5e5-9363-4bc9-9232-f925d3b9562c)

**Comment by piercemorris** [comment]
Personally I think adding a simple cross 'x' button to close the popup will suffice. Having looked at jidoujisho, it is primarily a mobile app which has a lot of the swipe functionality built into the package which makes it simple to implement.

**Comment by Xiphiasar** [comment]
Note that this X functionality already exists, but the X only shows up if you click a term within the yomitan popup to define it. The X shows up along with a forward and back arrow.

I agree it would be convenient to have the X from the start on mobile. Actually, as implemented, I would only want this feature on mobile because it would unnecessarily take up vertical space in the popup on desktop. So this might be best added as an option.

**Comment by Kuuuube** [comment]
> Note that this X functionality already exists, but the X only shows up if you click a term within the yomitan popup to define it. The X shows up along with a forward and back arrow.

Thanks for pointing this out! I've just checked and it can be forcibly enabled always by adding this css to `Popup CSS` in the `Custom CSS` setting:
```css
.content-sidebar {
    display: inherit;
}
```
