### ISSUE TITLE
Custom CSS Distributed With Dictionaries

### ISSUE THREAD

**Issue by MarvNC** [themoeway/yomitan#542]
> LGTM. (Though why does this work like this at all...? Wouldn't it make more sense for a dictionary to distribute some CSS (maybe with basic filtering to avoid remote resources) and then just refer to class names in the structured content...?)

_Originally posted by @djahandarie in https://github.com/themoeway/yomitan/pull/527#pullrequestreview-1821463382_

I always thought the same, it seemed quite limiting. Maybe the reason is compatibility with light and dark themes and ensuring a consistent experience by limiting what can be styled:

> Correct, this is the rationale for not originally adding them. That and they can't be themed easily by custom CSS, which leads to an inconsistent UI/UX. There is probably a better way to support this, such as by having the extension expose custom CSS vars for dictionaries to use for colors, but ultimately that would still just involve using custom string values for color/background-color.

_Originally posted by @toasted-nutbread in https://github.com/themoeway/yomitan/issues/450#issuecomment-1869227125_

**Comment by toasted-nutbread** [comment]
CSS scoping is an issue, if dictionaries are basically just injecting a `<style>` node with rules. If the CSS classes are defined in a way that is more similar to structured content, but having common type definitions for common classes, the issue is a bit different, in that there suddenly needs to be a way to store and retrieve that in the database.

Again the reason why it is _currently_ set up that way is because when I designed it, I did not foresee it growing into such a broadly used feature as it is today.

**Comment by djahandarie** [comment]
I think we have three options for scoping:
* Do some preprocessing or verification on the CSS to modify the selectors with some relevant scope, and/or verify that the appropriate scope is already on the class names (i.e., have a parent selector that matches on the dictionary name / revision id, etc etc.)
* Use a shadow DOM (not sure if it's possible)
* Use [@scope](https://developer.mozilla.org/en-US/docs/Web/CSS/@scope), but no Firefox support yet

**Comment by toasted-nutbread** [comment]
Shadow dom is possible but probably very ugly.
