### ISSUE TITLE
Disabling popup scanning if the to be scanned text is already the same as the parent one.

### ISSUE THREAD

**Issue by deewong7** [themoeway/yomitan#566]
I enabled the `Allow scanning search page content`, and found this unexpected behaviour, where a popup window shows even if the text to look up is the same as the parent one.

See the following screenshot for the detail. 
<img width="565" alt="image" src="https://github.com/themoeway/yomitan/assets/92027789/157182f9-8689-4b9e-9d1a-3f1a84754d1b">

**Comment by deewong7** [comment]
If anyone could provide guidance on which file I should use, I would be more than happy to create a PR.

**Comment by toasted-nutbread** [comment]
Search is currently prevented on the headwords to avoid the obvious search duplication, and some users may prefer to not have this prevented in general, as their nested popups may resolve definitions using a different dictionary by using profile conditions.

IMO not sure if this is worth adding the logic to prevent this case which I personally wouldn't consider to be invalid. This could also get complicated due to the nature of multiple definitions with multiple headwords being present. This could also be further complicated by inflected terms not being perfect matches to the headword, and potentially still appearing anyways.

ext/js/language/text-scanner.js is the file which performs the initial scanning.
