### ISSUE TITLE
Modern Browser Support

### ISSUE THREAD

**Issue by chimieria** [themoeway/yomitan#795]
Most modern browsers do not exclusively support webextensions or primarily use addons not based on webextensions. Chrome web store mandates WebExtensions but there is no reason the Firefox .dvi should be a webextension.

**Comment by andrewsartor** [comment]
I'd like more info here.

You reference that the Chrome web store mandates WebExtensions -- what exactly do you mean by this? The WebExtensions API is developed by Mozilla for Firefox to enable Chromium based browser cross compatibility ([ref](https://extensionworkshop.com/documentation/develop/about-the-webextensions-api/)). Furthermore, per their own documentation, they **must** be used when developing Firefox extensions (2017 - ) ([ref](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons#developing_extensions)).

Frankly, I'm not sure what the ask is here, and since there hasn't been any action on this in the past 3 weeks, I think further clarifying is necessary before anyone could pick this up.

**Comment by chimieria** [comment]
3 weeks without a response is disappointing but what I was trying to get across was that, like you said the webextension API is for chromium based cross compatibility. Since an exclusive chromium package is already being built, then the "firefox" extension doesnt need to be a web extension since in reality not all gecko browsers support web extensions based extensions.

**Comment by Kuuuube** [comment]
> 3 weeks without a response is disappointing

The main dev(s) have been busy with other things and havent had time to work on yomitan. And while yomitan is still being actively maintained by everyone else it's hard to give any concrete answers to things such as architecture changes.

**Comment by Kuuuube** [comment]
Yomitan does use the web extension api in Firefox. Changing this would require considerable work for seemingly next to zero gain.

Chrome, Firefox, Safari, Opera, and Edge all support the webextension api. This is roughly 96.5% of the desktop browser market share. (not including other smaller chromium-based browsers which also support webextension)

If you have more information about which modern browsers (with any substantial userbase) require the extension to not be a web extension and can demonstrate a trivial way to allow Yomitan to support these, feel free to reopen this issue.
