### ISSUE TITLE
Make Anki card with only one dictonary entry or definition instead of using all entries and definitions from the dictonaries

### ISSUE THREAD

**Issue by AdriGrana** [themoeway/yomitan#797]
Hello Yomitan Team,

I've been using Yomitan for creating Anki cards and I've encountered a workflow issue that I believe could be improved. Currently, when generating Anki cards, I find myself manually editing out unwanted dictionary entries and definitions. The dictionary I prefer varies with each card, making it impractical to rely on a single dictionary profile. While I appreciate the comprehensive information provided by multiple dictionaries for cross-comparison, directly importing all this data into Anki cards is suboptimal.

### Feature Proposal:

I propose adding functionality to allow users to select specific dictionary entries to be included in the Anki card. This could potentially be implemented in two ways:

1.  **Selective Dictionary Entry**: Introduce a '+' button next to each dictionary entry, enabling users to choose which entries to add to their Anki card. This approach seems more feasible and would significantly enhance the user experience by reducing the time spent on manual editing.

**Example 1**: 

![idea_1](https://github.com/themoeway/yomitan/assets/63470662/ea9cc81e-9548-4245-a7e0-117ae97697e0)

2. **Selective Definition within an Entry**: Allow users to select specific definitions within a dictionary entry for inclusion. While this offers even greater flexibility, I understand that the varied formatting across dictionaries might make this option more challenging to implement.

**Example 2**: 

![idea_2](https://github.com/themoeway/yomitan/assets/63470662/588a9d74-b214-44e3-84e7-8a833f138e28)

I realize the second suggestion might be more complex due to the diversity in dictionary formatting, so I can understand if that isn't really possible to implement, but the first suggestion should be possible I think.

**Additional Considerations**:

- The placement of the '+' buttons in the UI is just a suggestion; their final placement should be wherever it's most intuitive.
- Implementing this feature might introduce additional UI elements, potentially cluttering the search page. To address this, an option could be added in the settings to toggle this feature on or off, according to the user's preference.

I believe these enhancements could greatly improve the efficiency and customization of creating Anki cards with Yomitan, making it an even more valuable tool for language learners. Thank you for considering my proposal, and I look forward to any feedback or thoughts on this suggestion.

**Comment by linkofinsanity19** [comment]
This, especially the second option, would save me so much time, especially if we had the setting available to only add the text without formatting so that we can have our cards formatted the way we like. Anki is only useful for small pieces of info at a time, and entire dictionary entries are far from that. This would be the single biggest upgrade to Yomitan tha ti could think of, in addition to allowing us to add things without any formatting.

**Comment by foxmean** [comment]
I think your requested feature is already implemented with 'No grouping' dictionary in Setting>General as in picture below.

![Screenshot 2024-05-21 at 22 12 23](https://github.com/themoeway/yomitan/assets/13077459/da452e3d-66e2-4b47-8708-3ba369b2631b)

The result after use that option is something like the picture below, which is my current setting.
![Screenshot 2024-05-21 at 22 13 21](https://github.com/themoeway/yomitan/assets/13077459/c8333924-11e7-4e66-af0f-a039195f3a0d)

**Comment by linkofinsanity19** [comment]
I think maybe I didn't clarify myself very well. What I mean is that when adding a cards where a word in Japanese may have a lot of entries that can all be viable translations of the Japanese word, depending on the context, I'm saying that the ability to simply click (or Ctrl+click, or whatever you can make work) each individual entry to only include those when you click the + button, or maybe just have a plus button to each individual entry could also be fine I guess. 

By entry, I'm referring to, if we use the screenshot above as an example, the 9 separate words in the bullet points. I prefer to make cards for their specific context, rather than trying to have 9 different things to try to remember, |I just keep the 1-3 words that seem to fit the context I found them in best. For example, maybe when I'm mining I come across a sentence where leeway and margin work pretty well, but I thing scope and flexibility aren't helpful for that particular context, but rather I could make a separate card in the future for those when they seem better fitting to that context.

In this scenario, I'm sayin that the end result would be that I simply click on "leeway", then "margin", then "+" and then Yomitan would create the card in Anki, without any bullets, indents, etc, no formatting, just the 2 words I want, maybe with a comma or semicolon separating entries so that my created cards respect the formatting of my card templates so that I don't have to go into each individual card, remove the formatting, then separate them by commas, just so that they have a simple no frills formatting in my cards.

Do you see what I'm saying now? Basically the option to pick exactly which words go on cards and not have a predetermine left aligned bullet point format but rather plain text in the "English" field separated by commas so that my card template can determine how they will be displayed.

**Comment by Kuuuube** [comment]
I don't think this will every be added due to dictionaries not all being formatted the same. You can use the `selection-text` handlebar to select the part you want and only send that to the card.

**Comment by Kuuuube** [comment]
Closing this issue. If you have problems with using the `selection-text` handlebar for this use case please make another issue.
