### ISSUE TITLE
Replace all occurrences of yomichan with yomitan

### ISSUE THREAD

**Issue by djahandarie** [themoeway/yomitan#86]
Such as those in:
* documentation
* package.json, ext/manifest.json
* various user-facing strings throughout the projects
* (optionally) code, like module names and variable names (lowest priority, but there may not be many of these in the first place)

**Comment by djahandarie** [comment]
@Timm04 Took a quick look at your commit in your branch, a few comments:

* I see that you are breaking links (because `FooSoft/yomitan` is not a pjrect lol). We would need to first replace links (`FooSoft/yomichan` -> `themoeway/yomitan`), and then go through and do all the other occurrences after that I think.
* For non-links, many of those will need extra attention too. E.g., "Yomichan Import" → "Yomitan Import" is not a valid replacement because the latter project does not exist yet, etc.

I think basically every replacement will need to be hand-done or hand-checked at least.

**Comment by djahandarie** [comment]
Sidenote, I made the following PR to make this refactoring slightly safer:
* #89

**Comment by Timm04** [comment]
> @Timm04 Took a quick look at your commit in your branch, a few comments:

@djahandarie 
Jeah sorry, I realised that as well directly after I confirmed the changes. I didn't want to change it immediately since, from what I understand, its not a good practise to have seperate multiple edits/commits of the same file just because of one mistake, so I wanted to change that the coming days when I would update the other files as well. 
Please correct me if im wrong, can I just correct my mistake immediately after a commit with another commit or is this considered bad?
Sorry again, I will be more attentive!

**Comment by therealgrumpythomas** [comment]
@Timm04 I think it's fine to create new commits fixing oversights from previous ones. Some advanced git users like to [squash](https://git-scm.com/docs/git-rebase) their commits together into a single commit in order to keep the history clean. It comes with its [own risks](https://git-scm.com/docs/git-rebase#_notes)

**Comment by therealgrumpythomas** [comment]
On a side note. We could change the homepage value in `package.json` to point to this repository. Another option could be to have a dedicated page on https://learnjapanese.moe/ for yomitan

**Comment by therealgrumpythomas** [comment]
License changes in #99

**Comment by xythh** [comment]
Yomitan-Import exists now https://github.com/themoeway/yomitan-import/.

**Comment by Aquafina-water-bottle** [comment]
#97 and #98 changes most front-facing strings. @Timm04 If you have the time, would you mind merging your branch with master, and then making a PR with your branch (even if it's incomplete?) I think almost everything is renamed at this point.

**Comment by djahandarie** [comment]
Fixed by #314
