### ISSUE TITLE
[Help request]: Trying to add Safari support by running `xcrun safari-web-extension-converter` on yomitan

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan#949]
Can someone try to do this on their mac and report back their results on whether yomitan would work on their safari? 

Documentation: https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari/

Another blog post about the process: https://iboysoft.com/tips/convert-chrome-extension-to-safari.html

Related: #66

**Comment by ellieglad** [comment]
Attempted to do this, following the documentation, and the results are the same as in #66 .
Noted issues: Yomitan seems to correctly scan the text, but the results popover is not appearing, despite disabling both `Use a secure container around popups` and `Use secure popup frame URL`.  

`Enable background clipboard text monitoring` is also not permitted to be enabled, this might be due to having to grant new entitlements after converting to a safari web extension.

I could also not get the `import dictionary collection` option to work, as it hung partway into importing. Importing a few individual dictionaries seemed to work, though I did not check if it also started hanging after a certain amount of dictionaries were imported.

**Comment by jamesmaa** [comment]
Thank you for investigating this! Could you post your findings in #66 while I close out this issue (that I'm treating as a task)?

**Comment by ellieglad** [comment]
Done!
